### ISSUE TITLE
[VCert 5.0-rc1] \\VED\\Policy -- should be able to optionally include in the the

### ISSUE THREAD

**Issue by tall27** [Venafi/vcert#319] opened 2023-07-26 19:05 UTC
**PROBLEM SUMMARY**
vcert should be able to ignore \\VED\\Policy prefix if it is included in the zone tag. 

**STEPS TO REPRODUCE**
I added under zone: "\\VED\\Policy\\Certificates\\mytestfolder" tag and got an error.
once I remove leading "\\VED\\POLICY"everything worked.

**EXPECTED RESULTS**

**ACTUAL RESULTS**

**ENVIRONMENT DETAILS**
**[VCert 5.0-rc1]**

**COMMENTS/WORKAROUNDS**

**Comment by luispresuelVenafi** [comment] 2023-07-26 19:09
Hi @tall27,

Could you add more verbose steps to reproduce the issue?
Were you using VCert CLI or SDK?
Which version of VCert (it's the same for both VCert CLI and SDK)?
So from what I see on what you shared, you are using TPP, which version?

**Comment by tall27** [comment] 2023-07-26 19:38
Hi,
I'm using vcert 5.0 prerelease amd I reference to the 'run' option that uses yaml file:

            organization: Venafi Inc
            province: Utah
        **zone: Certificates\vcert\WebServer**

If I add start the zone: with \ved\policy\Certificates\vcert\WebServer the vcert fail to run.
here is an error:
```
2023-07-26T14:37:49.745-0500    INFO    service/service.go:48   Flag [force-renew] is set. All certificates will be requested/renewed regardless of status
vCert: 2023/07/26 14:37:49 You specified a trust bundle.
2023-07-26T14:37:49.889-0500    ERROR   vcert/playbook.go:140   error running task      {"task": "apache", "error": "error requesting certificate apache: vcert error: your data contains problems: zone not found"}
```

**Comment by luispresuelVenafi** [comment] 2023-07-26 20:16
Oh I see, thank you for clarifying. I'll tag this as part of VCert 5.0 found bugs

**Comment by rvelaVenafi** [comment] 2023-08-03 19:54
Closing this issue as not a bug

**Closed by rvelaVenafi** 2023-08-03 19:54 UTC
Labels: bug, vcert5dot0-prerelease
