### ISSUE TITLE
VCert not able to request cert

### ISSUE THREAD

**Issue by hashar1** [Venafi/vcert#2] opened 2018-12-13 03:01 UTC
Cert enrollment through vcert does not work.
Able to enroll cert with same user to same policy container only with common name with WebSDK API using Postman
Wireshark trace shows only Client Hello packet, no response as server Hello.
There is no proxy at client running vcert using latest 3.18.3.1
Server is TLS1.0 enabled same as client.

**Comment by arykalin** [comment] 2018-12-13 10:15
Hi @hashar1 do you have any error output from vcert? On what OS you're running it? Could you give the command with which you trying to enroll certificate?

**Comment by tr1ck3r** [comment] 2018-12-13 15:58
Also, please review the prerequisites listed on https://support.venafi.com/hc/en-us/articles/217991528-Introducing-VCert-API-Abstraction-for-DevOpsSec.  VCert was designed to minimize input data requirements by adhering to policy best practices of the Venafi Platform.

**Comment by hashar1** [comment] 2018-12-13 21:49
Thanks fore responding. This is the request and response, prerequisites are already set:
C:\Windows\system32>vcert enroll -tpp-url https://sss-tpp01.sss.co.nz -tpp-user chris -cn sss-test.sss.co.nz -z "Install 
ations" -key-password P@ssw0rd

vCert: 2018/12/03 12:52:38 Unable to connect to TPP: Post https://sss-tpp01.sss.co.nz/vedsdk/authorize/: read tcp 192.16 
8.50.137:10838->192.168.50.134:443: wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by tr1ck3r** [comment] 2018-12-14 05:31
Thank you @hashar1.  It looks like VCert is probably not able to complete the TLS handshake.  If you browse to https://tppurl/vedsdk from the computer on which you are running VCert, do you get any certificate errors?  Often the cause of issues like this is that none of the names in the WebSDK server certificate match the name being used in the -tpp-url parameter value or the WebSDK server certificate isn't trusted by the client (the computer where VCert is running).  For the latter you can either trust it at the operating system level or you can use the -trust-bundle option to specify a PEM file that contains the CA certificate that will establish trust.

**Comment by hashar1** [comment] 2018-12-18 00:59
Thanks @tr1ck3r 
When accessed vedsdk url through browser from the computer running VCert, it did not gave cert error. Certificate, intermediate and root CA cert are trusted and available in CAPI store. We have also tried trusting the PEM through -trust-bundle option in VCert. But still getting the same error.

**Comment by hashar1** [comment] 2018-12-18 05:02
Also certificate authentication is not enabled for VedSDK in IIS

**Comment by hashar1** [comment] 2018-12-20 00:41
@arykalin 
They have tried by executing VCert from TPP server as well, and got same wsarecv error. Filehash also matches 3.18.3.1 version:
SHA256 1CFA4B3F65DC46B6A03E9CF9EC2BFA6D7B528548CFE81637433B0BC0E1C841B3

**Comment by tr1ck3r** [comment] 2018-12-20 01:03
@hashar1 Have they tried the Linux or macOS versions of VCert?  I'm wondering if this is a Windows only issue.  Can they authenticate using PowerShell? (first line is commented out because they shouldn't need it if TLS 1.0 is enabled as you said in your first post)

```
#[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
$url = "https://tpp.venafi.example/vedsdk/authorize"
$body = @{ Username="local:admin"; Password="passw0rd" } | ConvertTo-Json
Invoke-RestMethod -Method Post -Uri $url -Body $body -ContentType "application/json" -UseBasicParsing
```

**Comment by hashar1** [comment] 2019-01-25 05:36
Yes they have tried on Linux which also dint work, as per them, it struggles with something at the server end.
And they were able to authenticate using PowerShell, but they had to remove '-useBasicParsing' for it to work.
with 'UseBasicParsing', they were getting below error:
PS C:\Windows\system32> C:\Temp\tls.ps1 
Invoke-RestMethod : A parameter cannot be found that matches parameter name 'UseBasicParsing'. 
At C:\Temp\tls.ps1:4 char:86 
+ ... lication/json" -UseBasicParsing 
+ ~~~~~~~~~~~~~~~~ 
+ CategoryInfo : InvalidArgument: (:) [Invoke-RestMethod], ParameterBindingException 
+ FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by tr1ck3r** [comment] 2019-01-25 07:39
@hashar1 The UseBasicParsing error is fine, sometimes it is needed and sometimes not.  What was the error message when VCert was run from Linux?

Next step is probably to capture a network trace using Wireshark from the client machine (where VCert is executed) that we can review.  Do you know if any hardening has been done to the TPP server?

**Comment by dumitru-gutu-absa** [comment] 2019-02-05 13:04
Hello @tr1ck3r @arykalin. Not yet sure but can I specify what CA I want to use when enrolling the certificate by calling vcert with params? Thx.

**Comment by arykalin** [comment] 2019-02-05 13:35
Hello @dumitru-gutu-absa no. You should specify CA template in your Venafi Platform policy. You can create multiple policies with different CA templates and choose them in vCert.

**Comment by dumitru-gutu-absa** [comment] 2019-02-05 13:58
> Hello @dumitru-gutu-absa no. You should specify CA template in your Venafi Platform policy. You can create multiple policies with different CA templates and choose them in vCert.

Based on [https://support.venafi.com/hc/en-us/articles/217991528-Introducing-VCert-API-Abstraction-for-DevOpsSec](url), I can't specify CA template but only the Policy folder which in the end has some CA template defined. Please correct me if I'm wrong.

**Comment by tr1ck3r** [comment] 2019-02-05 15:49
@dumitru-gutu-absa you are correct, the CA template must be assigned by policy (zone).  This aligns with Venafi best practices for Trust Protection Platform deployments.  The Venafi administrator provides different CA choices to the VCert user by providing them different zones to use when requesting certificates.

**Comment by dumitru-gutu-absa** [comment] 2019-02-06 15:28
@tr1ck3r @arykalin Thx for a lot for explanations 👍

**Comment by tr1ck3r** [comment] 2019-02-07 03:42
@hashar1 I'm going to close this issue because I think we're pretty confident that the connectivity issue that started this thread is due to a handshake failure to negotiate a common cipher suite.  I'll continue to work that issue with you internally.

**Closed by tr1ck3r** 2019-02-07 03:42 UTC

**Comment by hashar1** [comment] 2019-02-07 05:04
@tr1ck3r Thanks for all your help on this
