### ISSUE TITLE
vcert returns "private key error(3): asn1: structure error: integer not minimally-encoded" error on pickup/PKCS12

### ISSUE THREAD

**Issue by aburtonwoods** [Venafi/vcert#20] opened 2019-03-29 12:04 UTC
When issuing and retrieving certificates using vcert, occasionally the pickup process fails with "integer not minimally encoded" (more complete output below).

The failure is consistent, in that any given pickup ID will either always work, or always fail. Retrying makes no difference, which seems to imply that there is some byte sequence being returned from the API which triggers the bug during ASN.1 handling related to the PKCS#12 export.

The same certificate can be downloaded successfully (in PKCS#12) using the Aperture UI - this problem only exists when using vcert pickup.

Anecdotally, of 12 new certificates issued, only one of them triggered this problem on pickup. All the others worked fine.

vcert output (anonymised):
vcert pickup -verbose -pickup-id-file certname.pickup -tpp-url https://vedadmin.example.com/vedsdk -tpp-user tppuser -tpp-password somepassword -z 'PKI\StdCert\' -key-password reallygoodpassphrase -chain root-first -format pkcs12 -timeout 15 -file certname.p12
2019/03/29 11:00:41 Got 200 OK status for POST https://vedadmin.example.com/vedsdk/authorize/
vCert: 2019/03/29 11:00:41 Successfully connected to TPP
2019/03/29 11:00:41 Got 200 OK status for POST https://vedadmin.example.com/vedsdk/certificates/retrieve
vCert: 2019/03/29 11:00:41 Successfully retrieved request for \VED\Policy\PKI\StdCert\certname
vCert: 2019/03/29 11:00:41 Failed to output the results: failed to encode pkcs12: private key error(3): asn1: structure error: integer not minimally-encoded

**Comment by mr-tron** [comment] 2019-03-29 12:28
Can you send certificate to our email opensource@venafi.com? 
For example you can change [trace](https://github.com/Venafi/vcert/blob/master/pkg/venafi/tpp/tpp.go#L271) variable to `true`, recompile vcert, and send `vedsdk/certificates/retrieve` response to us.

**Comment by aburtonwoods** [comment] 2019-03-29 14:09
Many thanks for looking into this.
Just recompiled tpp.go with the trace option set, and and mailed the output.

**Comment by mr-tron** [comment] 2019-04-01 13:44
Very interesting. It looks like a bug in golang  `x509.DecryptPEMBlock` function.
Is this private key and password strongly secured? Can I use it as example in bug for google developers?

**Comment by aburtonwoods** [comment] 2019-04-01 14:30
Thanks for asking.
If it will be made public, then we'll need to find another way unfortunately. Even though the private key is well secured - this is an internal certificate which uses an internal domain name which we do not wish to publish.

If it helps, I can try to generate a bunch of test certificates with harmless names, and see if one can be made to fail on pickup?

**Comment by mr-tron** [comment] 2019-04-01 17:56
I don`t need to sharing certificate - only private key and password for private key. It will not disclosure any domain name, company info or over data.

**Comment by aburtonwoods** [comment] 2019-04-01 20:59
That resolves my only concern. Please feel free to use the key and passphrase as needed. I will revoke and reissue on my side.
Thanks again.

**Comment by mr-tron** [comment] 2019-04-02 13:26
I have reproduced task locally. We work for fixing it.

**Comment by shriramsharma** [comment] 2019-10-01 17:00
👍

**Comment by mr-tron** [comment] 2019-12-19 17:54
It fixed in Venafi Trusted Platform 19.3. 
It is not require any fixes in vcert library.

**Closed by mr-tron** 2019-12-19 17:54 UTC
Labels: VEN-48308, bug
